  version: '3.8'
  services:
    db:
      image: postgres
      environment:
        POSTGRES_DB:  poll
        POSTGRES_USER: pollbuddy
        POSTGRES_PASSWORD: njuca226
      volumes:
        - ./postgres_data/data:/var/lib/postgresql/data
      
    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      ports:
        - "8000:8000"
      volumes:
        - ./app:/code/app/ 
      depends_on:
        - db
      
  volumes:
    postgres_data:
